[tool.bumpversion]
current_version = "0.0.0"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
search = "{current_version}"
replace = "{new_version}"
regex = false
ignore_missing_version = false
ignore_missing_files = false
tag = false
sign_tags = true
tag_name = "v{new_version}"
tag_message = "release: {new_version}"
allow_dirty = false
commit = true
message = "release:{new_version}"
moveable_tags = []
commit_args = "--no-verify"

[tool.bumpversion.files]
filename = "docs/index.md"
