default_language_version:
  python: python3.12
default_install_hook_types:
  - pre-commit
  - commit-msg
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier

  - repo: https://github.com/fsouza/autoflake8
    rev: v0.4.1
    hooks:
      - id: autoflake8
        args:
          - "--in-place"
          - "--remove-unused-variables"
          - "--exclude=**/settings/*"
          - "--exclude=**/__init__.py"

  - repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          - "--force-single-line-imports"
          - "--line-length=120"

  - repo: https://github.com/aristanetworks/j2lint
    rev: v1.1.0
    hooks:
      - id: j2lint

  - repo: https://github.com/mrtazz/checkmake
    rev: 0.2.2
    hooks:
      - id: checkmake

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.5.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
