FROM public.ecr.aws/docker/library/python:{{ project_python_version }}
RUN mkdir /app
WORKDIR /app
COPY ./setup.py .
COPY ./pyproject.toml .
COPY ./requirements/production.txt requirements.txt
RUN pip install -r requirements.txt
COPY ./{{ project_name }} .
RUN pip install .
